# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, default='', max_length=300, verbose_name='Header text')),
                ('left_top', models.CharField(blank=True, default='', max_length=200, verbose_name='Ad-1: Top Left')),
                ('left_bottom', models.CharField(blank=True, default='', max_length=200, verbose_name='Ad-2: Bottom Left')),
                ('right_top', models.CharField(blank=True, default='', max_length=200, verbose_name='Ad-3: Top Right')),
                ('right_bottom', models.CharField(blank=True, default='', max_length=200, verbose_name='Ad-4: Bottom Right')),
                ('footer', models.CharField(blank=True, default='', max_length=300, verbose_name='Footer Text')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
