# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsdetails',
            name='update_flag',
            field=models.BooleanField(default=True),
        ),
    ]
