# Generated by Django 2.1.1 on 2018-09-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localpi', '0002_adsdetails_update_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsdetails',
            name='update_flag',
        ),
    ]
