# Generated by Django 2.1.1 on 2018-10-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpi', '0003_remove_adsdetails_update_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsdetails',
            name='update_flag',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
