# Generated by Django 2.1.1 on 2018-10-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localpi', '0004_adsdetails_update_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsdetails',
            name='actual_client_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
