# Generated by Django 2.1.1 on 2018-10-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localpi', '0005_adsdetails_actual_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsdetails',
            name='actual_client_id',
        ),
    ]
