# Generated by Django 2.1.1 on 2018-10-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localpi', '0006_remove_adsdetails_actual_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsdetails',
            name='client_id',
        ),
    ]
